In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from repo_training_codellm.FiD.src.options import Options

In [3]:
options = Options()
options.add_reader_options()
options.add_optim_options()
opt = options.parse([
    '--config', '/home/toolkit/code/repo_training_codellm/conf/test_reader_training.yaml',
    '--model_name', 't5',
    '--train_data', '/repo_data/open_domain_data/NQ/train.json',
    '--eval_data', '/repo_data/open_domain_data/NQ/train.json'
])

In [4]:
opt

Namespace(config='/home/toolkit/code/repo_training_codellm/conf/test_reader_training.yaml', name='experiment1', checkpoint_dir='/home/toolkit/checkpoints1/repo_training_codellm', model_path='none', per_gpu_batch_size=1, maxload=10, local_rank=-1, main_port=8080, seed=42, eval_freq=1, save_freq=1, eval_print_freq=1, model_name='t5', train_data='/repo_data/open_domain_data/NQ/train.json', eval_data='/repo_data/open_domain_data/NQ/train.json', model_size='base', use_checkpoint=False, text_maxlength=200, answer_maxlength=-1, no_title=False, n_context=1, warmup_steps=1000, total_steps=1000, scheduler_steps=None, accumulation_steps=1, dropout=0.1, lr=0.0001, clip=1.0, optim='adam', scheduler='fixed', weight_decay=0.1, fixed_lr=False)

In [5]:
import sys
sys.path.insert(0,"/home/toolkit/code/repo_training_codellm/FiD")
# train_reader uses import src.something so we need to insert FiD root here
from repo_training_codellm.FiD.train_reader import run

In [ ]:
run(opt)

/home/toolkit/.conda/envs/rlctx_p39/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5.py:163: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(


[02/27/2023 14:08:41] {train_reader.py:197} INFO - Start training


/home/toolkit/.conda/envs/rlctx_p39/lib/python3.9/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/toolkit/.conda/envs/rlctx_p39/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:2339: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size

In [ ]:
import torch.utils.tensorboard
from pathlib import Path
tb_logger = torch.utils.tensorboard.SummaryWriter(Path(opt.checkpoint_dir)/opt.name)

In [ ]:
tb_logger

In [4]:
from transformers import RobertaTokenizer, T5ForConditionalGeneration

tokenizer = RobertaTokenizer.from_pretrained('Salesforce/codet5-base')
model = T5ForConditionalGeneration.from_pretrained('Salesforce/codet5-base')

text = "package com.icommerce.<extra_id_0>"
input_ids = tokenizer(text, return_tensors="pt").input_ids

# simply generate one code span
generated_ids = model.generate(input_ids, max_length=8)
print(tokenizer.decode(generated_ids[0], skip_special_tokens=True))

csharp.c


In [1]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen-2B-multi")
model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen-2B-multi")
print(tokenizer.eos_token_id)
text = "public"
outs = tokenizer(text)
print(outs['input_ids'])
# simply generate one code span
#generated_ids = model.generate(input_ids, max_length=10)
print(tokenizer.decode(outs, skip_special_tokens=True))

/home/toolkit/.conda/envs/repo_training/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


50256
[11377, 220, 50256]


TypeError: argument 'ids': 'dict' object cannot be converted to 'Sequence'

In [3]:
a = [1, 2, 3, 4]
c = a.pop(0)
print(a, c)
r = a[:0]
r.append(c)
print(r)

[2, 3, 4] 1
[1]


In [22]:
from text_generation import Client
client = Client("https://snow-llmd-snow_dzmitry_llmd_bigcode_job.job.console.elementai.com", \
    headers={"Authorization": "Bearer MXdEynxiBoSn2nCejb4YMcYl-I9Mr99np_8LsH1o0F8.u_uIz2VmqDy6Ow-KU00kkBtNAIhWWB9K39KrVUgbB6U"})

input = "public static " 
print(len(input))
response = client.generate(input, max_new_tokens=10)
print(response)

14


JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [17]:
from transformers import AutoModelForCausalLM, AutoTokenizer
access_token = "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"
tokenizer = AutoTokenizer.from_pretrained("bigcode/large-model", use_auth_token=access_token)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.padding_side = 'left'

In [1]:

from transformers import AutoModelForCausalLM, AutoTokenizer

checkpoint = "bigcode/large-model"
device = "cpu" # for GPU usage or "cpu" for CPU usage

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForCausalLM.from_pretrained(checkpoint, trust_remote_code=True).to(device)





/home/toolkit/.conda/envs/repo_training/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


OSError: bigcode/large-model is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

In [5]:
input_text = "<fim-prefix>def print_hello_world():\n    <fim-suffix>\n    print('Hello world!')<fim-middle>"
inputs = tokenizer.encode(input_text, return_tensors="pt").to(device)
outputs = model.generate(inputs, max_length=100)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


def print_hello_world():
    
    print('Hello world!')"""Prints hello world."""e.log(err);
    }
  }
}

module.exports = {
  get,
  post,
  put,
  delete: _delete
};
const axios = require('axios');
const {
  API_URL,
  API_KEY
} = require('../config');

const get = async (url, params)


In [12]:
print(tokenizer("\n", return_tensors="pt").input_ids)
print(tokenizer("\r", return_tensors="pt").input_ids)
print(tokenizer("<fim-suffix>", return_tensors="pt").input_ids)

tensor([[185]])
tensor([[188]])
tensor([[49155]])


In [23]:
import os
import openai
#openai_api_key = "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"
os.environ["OPENAI_API_KEY"] = open('/home/toolkit/repo_training_codellm/openai_api_key', 'r').read().strip()
openai.api_key = os.getenv("OPENAI_API_KEY")
openai.organization = "org-yPiFS0ZBT0mAkDrSnMPvfYap"

def generate_prediction(prompt):
  '''
  generate predictions using Codex
  '''
  #try:
  response = openai.ChatCompletion.create(model="gpt-3.5-turbo",\
                                        messages = [
                                            {"role": "system", "content": "In the following conversation, whenever you are given an incomplete snippet of Java code, you will complete it until the end of the line. I only want a single line of output."},
                                            {"role": "user", "content": prompt},
                                        ], \
                                        max_tokens=128,\
                                        temperature=0.0)

  #except:
  #  print ("Waiting")
  #  response = None
  return response
  
response = generate_prediction("public statis void ma")
response.choices[0].message.content


'in(String[] args) {\n    System.out.println("Hello World!");\n}'